# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Parchment
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Minecraft / NeoForge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.251
loader_version_range=[1,)

# Tierworks
mod_id=tierworks
mod_name=Tierworks
mod_license=Apache-2.0
mod_version=0.10
mod_group_id=io.github.maxwelljones.tierworks
